### ISSUE TITLE
Debugging on linux docker container

### ISSUE THREAD

**Issue by grest** [Microsoft/SmartHotel360-Website#6]
I'd like to debug the project on a linux docker container with Visual Studio. Unfortunately using docker-compose as the StartUp project isn't working. The Docker extension for Visual Studio builds the smarthotel360.publicweb:dev image with target base, without node for example. As the workaround I changed the docker file accordingly (merged "withnode" target with "base") but then I started having problems with sass, because of OS inconsistency (windows vs linux) and node.js version (9.x vs 6.x)

Any advice how to amend the dockerfile and docker-compose to be able to debug the project on a linux container?

**Comment by bradygmsft** [comment]
adding @eiximenis to this issue. could this be resolved or should i reach out to our friends in the tooling team to get some support?

**Comment by dsanchezcr** [comment]
Closing this issue since it is a feature request. Right now we don't have in our backlog adding more features to this app. You can take a look at [Tailwind Traders Website](https://github.com/Microsoft/TailwindTraders-Website
) that one is containerized and you will be able to use docker on Linux for running it.
